project:
  type: website

website:
  title: "Glen's Tours"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Experience.qmd
        text: Explore Our Tours
      - href: contact.qmd
        text: Book Now
    background: "dark"

